name: Deploy to Staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to development cluster
    runs-on: ubuntu-latest  # Specify a runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: SSH into Server and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@<your-server-ip> << 'EOF'
          cd DeployingTurborepo/
          git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server
          pm2 restart http
          pm2 restart ws
          EOF
